<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Personas [
  <!ELEMENT Personas (Persona+)>
  <!ELEMENT Persona (Nombre,Apellido,Contacto?)>
  <!ELEMENT Nombre (#PCDATA)>
  <!ELEMENT Apellido (#PCDATA)>
  <!ELEMENT Contacto (Email|Telefono)>
  <!ELEMENT Email (#PCDATA)>
  <!ELEMENT Telefono (#PCDATA)>
]>

<Personas>
<Persona>
  <Nombre>Juan</Nombre>
  <Apellido>Pérez</Apellido>
  <Contacto>
    <Email>juan.perez@example.com</Email>
  </Contacto>
</Persona>

<Persona>
  <Nombre>María</Nombre>
  <Apellido>González</Apellido>
  <Contacto>
    <Telefono>123-456-7890</Telefono>
  </Contacto>
</Persona>

<Persona>
  <Nombre>Carlos</Nombre>
  <Apellido>Rodríguez</Apellido>
</Persona>
</Personas>
