<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo.xslt"?>
<!DOCTYPE rss [
   <!ELEMENT rss (channel)>
   <!ATTLIST rss version CDATA #REQUIRED>
   <!ELEMENT channel (item+)>
   <!ELEMENT item (title,link,description)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT link (#PCDATA)>
   <!ELEMENT description (#PCDATA)>
]>

<rss version="2.0">
   <channel>
      <item>
      <title>Nuestra web</title>
      <link>http://www.miszapatos.com</link>
      <description>Pagina web lider de venta de zapatos</description>
       </item>

       <item>
          <title>Articulos nuevos</title>
          <link>http://www.miszapatos.com/novedades</link>
          <description>Ultimos articulos a√±adidos</description>
        </item>

       <item>
          <title>Ultimas noticias</title>
          <link>http://www.miszapatos.com/noticias</link>
          <description>Actualizaciones del sector</description>
       </item>
    </channel>
  </rss>