=== paucare/LGM/03_XML/ejerciciosRepaso/ejercicioIES/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

<!-- ComplexType IES-->
<xs:complexType name="iesType">
    <xs:sequence>
        <xs:element name="profesores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="profesor" type="profesorType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" type="alumnoType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    </xs:sequence>

    <xs:attribute name="nombre" type="xs:string"/>
    <xs:attribute name="ubicacion" type="xs:string"/>

</xs:complexType>

<!-- ComplexType Profesor -->
<xs:complexType name="profesorType">
        <xs:sequence>
        <xs:element name="asignaturas">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="asignatura" type="asignaturaType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        </xs:sequence>
        <xs:attribute name="nombre" type="xs:string"/>
        <xs:attribute name="apellidos" type="xs:string"/>
    </xs:complexType>


<!-- ComplexType Asignatura -->
<xs:complexType name="asignaturaType">
    <xs:sequence>
        <xs:element name="horas" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="nombre" type="xs:string"/>
</xs:complexType>

<!-- ComplexType Asignatura -->
<xs:complexType name="alumnoType">
    <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="edad" type="xs:integer"/>
    </xs:sequence>
</xs:complexType>


<!-- Elemento raÃ­z-->
<xs:element name="instituto">
<xs:complexType>
    <xs:sequence>
        <xs:element name="ies" type="iesType"/>
    </xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== paucare/LGM/03_XML/ejerciciosRepaso/ejercicioIES/instituto.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="estilo.xslt" type="text/xsl"?>
<!DOCTYPE instituto SYSTEM "instituto.dtd">
<!-- <instituto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd"> -->
    <instituto>
    <ies nombre="Instituto nacional de educación" ubicacion="Sevilla,España">
        <profesores>
            <profesor nombre="Laura" apellidos="García Martín">
                <asignaturas>
                    <asignatura nombre="matematicas">
                        <horas>5</horas>
                    </asignatura>
                    <asignatura nombre="fisica">
                        <horas>3</horas>
                    </asignatura>
                </asignaturas>
            </profesor>
            <profesor nombre="David" apellidos="Ruíz Fernández">
                <asignaturas>
                    <asignatura nombre="historia">
                        <horas>4</horas>
                    </asignatura>
                    <asignatura nombre="geografia">
                        <horas>2</horas>
                    </asignatura>
                </asignaturas>
            </profesor>
        </profesores>
        <alumnos>
            <alumno>
                <nombre>Clara</nombre>
                <apellidos>Sanchez Lopez</apellidos>
                <edad>17</edad>
            </alumno>
            <alumno>
                <nombre>Lucas</nombre>
                <apellidos>Martinez Perez</apellidos>
                <edad>16</edad>
            </alumno>
        </alumnos>
    </ies>
</instituto>
