=== paucare/LGM/03_XML/ejerciciosXSLT/ejercicioIES/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
<!-- ComplexType Instituto-->

<xs:complexType name="institutoType">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" minOccurs="1"/>
            <xs:element name="ubicacion" type="xs:string" minOccurs="1"/>
        
            <xs:element name="profesores">
            <xs:complexType>
                <xs:sequence>
                <xs:element name="profesor" type="profesorType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
            </xs:element>

            <xs:element name="alumnos">
            <xs:complexType>
                <xs:sequence>
                <xs:element name="alumno" type="alumnoType" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>
            </xs:element>
            
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="profesorType">
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellidos" type="xs:string"/>
                <xs:element name="asignaturas">
                    <xs:complexType>
                    <xs:sequence>
                    <xs:element name="asignatura" type="asignaturaType" maxOccurs="unbounded"/>
                </xs:sequence>
             </xs:complexType>
                </xs:element>
            </xs:sequence>
    </xs:complexType>

    <xs:complexType name="asignaturaType">
            <xs:sequence>
                <xs:element name="horas" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="alumnoType">
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellidos" type="xs:string"/>
                <xs:element name="edad" type="xs:integer"/>
            </xs:sequence>
    </xs:complexType>

<!-- Elemento RaÃ­z -->
<xs:element name="institutos">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="ies" type="institutoType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== paucare/LGM/03_XML/ejerciciosXSLT/ejercicioIES/ies.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo.xslt"?>

<institutos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd">
<ies>
    <nombre>Instituto nacional de Educación</nombre>
    <ubicacion>Sevilla,España</ubicacion>
    <profesores>
    <profesor>
        <nombre>Laura</nombre>
        <apellidos>Garcia Martin</apellidos>
        <asignaturas>
            <asignatura nombre="Matemáticas">
                <horas>
                    5 horas/semana
                </horas>
            </asignatura>
            <asignatura nombre="Física">
                <horas>
                    3 horas/semana
                </horas>
            </asignatura>
        </asignaturas>
    </profesor>
    <profesor>
        <nombre>David</nombre>
        <apellidos>Ruiz Fernández</apellidos>
        <asignaturas>
            <asignatura nombre="Historia">
                <horas>
                    4 horas/semana
                </horas>
            </asignatura>
            <asignatura nombre="Gegorafía">
                <horas>
                    2 horas/semana
                </horas>
            </asignatura>
        </asignaturas>
    </profesor>
    </profesores>
    <alumnos>
        <alumno>
            <nombre>Clara</nombre>
            <apellidos>Sánchez López</apellidos>
            <edad>17</edad>
        </alumno>
        <alumno>
            <nombre>Lucas</nombre>
            <apellidos>Martñinez Pérez</apellidos>
            <edad>16</edad>
        </alumno>
    </alumnos>
</ies>
</institutos>
